use super::seed_uuid;
use crate::db::Db;
use crate::types::{
    AreaData, AreaFlags, AreaPermission, CombatZoneType, ForageEntry, ImmigrationVariationChances, RoomFlags,
};
use anyhow::Result;

pub fn seed_areas(db: &Db) -> Result<()> {
    let areas = vec![
        AreaData {
            id: seed_uuid("area:oakvale"),
            name: "Oakvale Village".to_string(),
            prefix: "oakvale".to_string(),
            description: "A peaceful village nestled in a valley, serving as the central hub for adventurers. Cobblestone streets wind between timber-framed buildings, and the sound of a fountain echoes from the town square.".to_string(),
            level_min: 1,
            level_max: 5,
            theme: "medieval village".to_string(),
            owner: None,
            permission_level: AreaPermission::AllBuilders,
            trusted_builders: Vec::new(),
            city_forage_table: vec![
                ForageEntry { vnum: "oakvale:herb".to_string(), min_skill: 0, rarity: "common".to_string() },
            ],
            wilderness_forage_table: Vec::new(),
            shallow_water_forage_table: Vec::new(),
            deep_water_forage_table: Vec::new(),
            underwater_forage_table: Vec::new(),
            combat_zone: CombatZoneType::Safe,
            flags: AreaFlags::default(),
            default_room_flags: RoomFlags::default(),
            immigration_enabled: false,
            immigration_room_vnum: String::new(),
            immigration_name_pool: String::new(),
            immigration_visual_profile: String::new(),
            migration_interval_days: 0,
            migration_max_per_check: 0,
            migrant_sim_defaults: None,
            last_migration_check_day: None,
            immigration_variation_chances: ImmigrationVariationChances::default(),
            immigration_family_chance: crate::types::ImmigrationFamilyChance::default(),
        },
        AreaData {
            id: seed_uuid("area:whisperwood"),
            name: "Whispering Woods".to_string(),
            prefix: "whisperwood".to_string(),
            description: "An ancient forest where the wind carries whispered secrets through towering oaks. Sunlight filters through the dense canopy, illuminating moss-covered paths and hidden clearings.".to_string(),
            level_min: 2,
            level_max: 6,
            theme: "enchanted forest".to_string(),
            owner: None,
            permission_level: AreaPermission::AllBuilders,
            trusted_builders: Vec::new(),
            city_forage_table: Vec::new(),
            wilderness_forage_table: vec![
                ForageEntry { vnum: "oakvale:herb".to_string(), min_skill: 0, rarity: "common".to_string() },
                ForageEntry { vnum: "oakvale:apple".to_string(), min_skill: 0, rarity: "common".to_string() },
            ],
            shallow_water_forage_table: Vec::new(),
            deep_water_forage_table: Vec::new(),
            underwater_forage_table: Vec::new(),
            combat_zone: CombatZoneType::Pve,
            flags: AreaFlags::default(),
            default_room_flags: RoomFlags::default(),
            immigration_enabled: false,
            immigration_room_vnum: String::new(),
            immigration_name_pool: String::new(),
            immigration_visual_profile: String::new(),
            migration_interval_days: 0,
            migration_max_per_check: 0,
            migrant_sim_defaults: None,
            last_migration_check_day: None,
            immigration_variation_chances: ImmigrationVariationChances::default(),
            immigration_family_chance: crate::types::ImmigrationFamilyChance::default(),
        },
        AreaData {
            id: seed_uuid("area:ironkeep"),
            name: "Iron Keep".to_string(),
            prefix: "ironkeep".to_string(),
            description: "A formidable stone fortress perched on a rocky promontory. Iron-banded gates guard the entrance, and the clang of hammer on anvil rings from the armory within.".to_string(),
            level_min: 3,
            level_max: 8,
            theme: "castle fortress".to_string(),
            owner: None,
            permission_level: AreaPermission::AllBuilders,
            trusted_builders: Vec::new(),
            city_forage_table: Vec::new(),
            wilderness_forage_table: Vec::new(),
            shallow_water_forage_table: Vec::new(),
            deep_water_forage_table: Vec::new(),
            underwater_forage_table: Vec::new(),
            combat_zone: CombatZoneType::Safe,
            flags: AreaFlags::default(),
            default_room_flags: RoomFlags::default(),
            immigration_enabled: false,
            immigration_room_vnum: String::new(),
            immigration_name_pool: String::new(),
            immigration_visual_profile: String::new(),
            migration_interval_days: 0,
            migration_max_per_check: 0,
            migrant_sim_defaults: None,
            last_migration_check_day: None,
            immigration_variation_chances: ImmigrationVariationChances::default(),
            immigration_family_chance: crate::types::ImmigrationFamilyChance::default(),
        },
        AreaData {
            id: seed_uuid("area:shadowfang"),
            name: "Shadowfang Caves".to_string(),
            prefix: "shadowfang".to_string(),
            description: "A labyrinth of dark, twisting caverns beneath the Iron Keep. The air is thick with the stench of goblin camps and the skittering of unseen creatures.".to_string(),
            level_min: 5,
            level_max: 10,
            theme: "underground dungeon".to_string(),
            owner: None,
            permission_level: AreaPermission::AllBuilders,
            trusted_builders: Vec::new(),
            city_forage_table: Vec::new(),
            wilderness_forage_table: vec![
                ForageEntry { vnum: "shadowfang:mushroom".to_string(), min_skill: 1, rarity: "uncommon".to_string() },
            ],
            shallow_water_forage_table: Vec::new(),
            deep_water_forage_table: Vec::new(),
            underwater_forage_table: Vec::new(),
            combat_zone: CombatZoneType::Pve,
            flags: AreaFlags::default(),
            default_room_flags: RoomFlags::default(),
            immigration_enabled: false,
            immigration_room_vnum: String::new(),
            immigration_name_pool: String::new(),
            immigration_visual_profile: String::new(),
            migration_interval_days: 0,
            migration_max_per_check: 0,
            migrant_sim_defaults: None,
            last_migration_check_day: None,
            immigration_variation_chances: ImmigrationVariationChances::default(),
            immigration_family_chance: crate::types::ImmigrationFamilyChance::default(),
        },
        AreaData {
            id: seed_uuid("area:hilltop"),
            name: "Hilltop Farm".to_string(),
            prefix: "hilltop".to_string(),
            description: "A sprawling farm on a gentle hillside south of Oakvale. Rolling fields of golden wheat surround a weathered farmhouse, and the scent of fresh earth carries on the breeze.".to_string(),
            level_min: 1,
            level_max: 3,
            theme: "pastoral farmland".to_string(),
            owner: None,
            permission_level: AreaPermission::AllBuilders,
            trusted_builders: Vec::new(),
            city_forage_table: Vec::new(),
            wilderness_forage_table: vec![
                ForageEntry { vnum: "oakvale:apple".to_string(), min_skill: 0, rarity: "common".to_string() },
            ],
            shallow_water_forage_table: Vec::new(),
            deep_water_forage_table: Vec::new(),
            underwater_forage_table: Vec::new(),
            combat_zone: CombatZoneType::Safe,
            flags: AreaFlags::default(),
            default_room_flags: RoomFlags::default(),
            immigration_enabled: false,
            immigration_room_vnum: String::new(),
            immigration_name_pool: String::new(),
            immigration_visual_profile: String::new(),
            migration_interval_days: 0,
            migration_max_per_check: 0,
            migrant_sim_defaults: None,
            last_migration_check_day: None,
            immigration_variation_chances: ImmigrationVariationChances::default(),
            immigration_family_chance: crate::types::ImmigrationFamilyChance::default(),
        },
    ];

    for area in areas {
        db.save_area_data(area)?;
    }

    tracing::info!("Seeded 5 areas");
    Ok(())
}
