export const itemToolDefinitions = [
  {
    name: "list_items",
    description: "List items, optionally filtered by type",
    inputSchema: {
      type: "object",
      properties: {
        limit: { type: "number", default: 100 },
        offset: { type: "number", default: 0 },
        item_type: {
          type: "string",
          enum: ["misc", "armor", "weapon", "container", "liquid_container", "food", "key", "gold"],
        },
      },
    },
  },
  {
    name: "list_item_prototypes",
    description: "List only item prototypes (templates). WARNING: Returns full entity data. Prefer list_item_prototypes_summary for discovery.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "list_item_prototypes_summary",
    description: "List item prototype summaries (compact: vnum, name, type, weight, value). Use for discovery, then get_item by vnum for detail.",
    inputSchema: {
      type: "object",
      properties: {
        vnum_prefix: {
          type: "string",
          description: "Filter by vnum prefix (e.g., 'training' to match 'training:*')",
        },
      },
    },
  },
  {
    name: "get_item",
    description: "Get an item by UUID or vnum",
    inputSchema: {
      type: "object",
      properties: {
        identifier: { type: "string", description: "Item UUID or vnum" },
      },
      required: ["identifier"],
    },
  },
  {
    name: "create_item",
    description: "Create a new item prototype",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Item name" },
        short_desc: { type: "string", description: "Short description when on ground" },
        long_desc: { type: "string", description: "Full description when examined" },
        vnum: { type: "string", description: "Unique vnum (e.g., 'weapons:iron_sword')" },
        keywords: { type: "array", items: { type: "string" } },
        item_type: {
          type: "string",
          enum: ["misc", "armor", "weapon", "container", "liquid_container", "food", "key", "gold"],
        },
        weight: { type: "number", default: 1 },
        value: { type: "number", default: 0 },
        categories: {
          type: "array",
          items: { type: "string" },
          description: "Crafting / shop-filter categories (e.g., 'flowers', 'herbs', 'leather'). Used by shopkeepers' shop_buys_categories filter and by crafting recipes.",
        },
        wear_location: {
          type: "string",
          enum: ["head", "neck", "shoulders", "back", "torso", "waist", "ears",
                 "wielded", "offhand", "ready",
                 "leftarm", "rightarm", "leftwrist", "rightwrist",
                 "lefthand", "righthand", "leftfinger", "rightfinger",
                 "leftleg", "rightleg", "leftankle", "rightankle",
                 "leftfoot", "rightfoot"],
        },
        damage_dice_count: { type: "number", description: "For weapons: dice count (e.g., 2 in 2d6)" },
        damage_dice_sides: { type: "number", description: "For weapons: dice sides (e.g., 6 in 2d6)" },
        damage_type: {
          type: "string",
          enum: ["bludgeoning", "slashing", "piercing", "fire", "cold", "lightning", "poison", "acid"],
        },
        armor_class: { type: "number", description: "For armor: AC bonus" },
        flags: {
          type: "object",
          properties: {
            no_drop: { type: "boolean" },
            no_get: { type: "boolean" },
            invisible: { type: "boolean" },
            glow: { type: "boolean" },
            hum: { type: "boolean" },
            plant_pot: { type: "boolean" },
            lockpick: { type: "boolean", description: "Can be used to pick locks" },
            is_skinned: { type: "boolean", description: "Corpse has been butchered/skinned" },
            boat: { type: "boolean", description: "Allows traversing deep_water rooms when in inventory" },
            medical_tool: { type: "boolean", description: "Can be used for medical treatment" },
          },
        },
        caliber: { type: "string", description: "Firearm caliber (e.g., '9mm', '5.56')" },
        ranged_type: { type: "string", description: "Ranged weapon type (e.g., 'pistol', 'rifle')" },
        magazine_size: { type: "number", description: "Magazine capacity" },
        fire_mode: { type: "string", description: "Default fire mode (e.g., 'semi', 'auto', 'burst')" },
        supported_fire_modes: { type: "array", items: { type: "string" }, description: "All supported fire modes" },
        noise_level: { type: "string", description: "Noise level (e.g., 'loud', 'quiet', 'suppressed')" },
        two_handed: { type: "boolean", description: "Whether weapon requires two hands" },
        weapon_skill: {
          type: "string",
          enum: ["short_blades", "long_blades", "short_blunt", "long_blunt", "polearms", "unarmed", "ranged"],
          description: "Weapon skill category",
        },
        ammo_count: { type: "number", description: "Ammo: rounds in this ammo item" },
        ammo_damage_bonus: { type: "number", description: "Ammo: bonus damage per round" },
        attachment_slot: { type: "string", description: "Attachment: which slot this attaches to" },
        attachment_accuracy_bonus: { type: "number", description: "Attachment: accuracy bonus" },
        attachment_noise_reduction: { type: "number", description: "Attachment: noise reduction" },
        attachment_magazine_bonus: { type: "number", description: "Attachment: magazine size bonus" },
        plant_prototype_vnum: { type: "string", description: "For seeds: plant prototype vnum this seed grows into" },
        fertilizer_duration: { type: "number", description: "For fertilizer: duration in game hours" },
        treats_infestation: { type: "string", description: "For pest treatment: type treated (aphids, blight, root_rot, frost, all)" },
        liquid_type: { type: "string", description: "For liquid_container: liquid type (water, ale, wine, beer, spirits, alcohol, milk, juice, tea, coffee, etc.). Default effects auto-applied unless `liquid_effects` is also passed." },
        liquid_current: { type: "number", description: "For liquid_container: current sips" },
        liquid_max: { type: "number", description: "For liquid_container: maximum sips" },
        liquid_effects: {
          type: "array",
          description: "For liquid_container: explicit effects when drunk. If omitted, defaults for the liquid_type are auto-applied. If provided, overrides defaults entirely.",
          items: {
            type: "object",
            properties: {
              effect_type: { type: "string", description: "Effect type: heal, poison, stamina_restore, mana_restore, satiated, quenched, drunk, str_boost, dex_boost, con_boost, int_boost, wis_boost, cha_boost, haste, slow, invisibility, detect_invisible, regeneration" },
              magnitude: { type: "number", description: "Effect strength" },
              duration: { type: "number", description: "Duration in seconds (0 = instant)" },
            },
            required: ["effect_type", "magnitude"],
          },
        },
        medical_tier: { type: "number", description: "Medical tier: 1=basic, 2=intermediate, 3=advanced" },
        medical_uses: { type: "number", description: "Medical uses: 0=reusable, >0=consumable" },
        treats_wound_types: { type: "array", items: { type: "string" }, description: "Wound types this item treats (e.g., 'cut', 'burn', 'fracture')" },
        food_nutrition: { type: "number", description: "For food: nutrition value (how filling)" },
        food_spoil_duration: { type: "number", description: "For food: spoilage time in game hours (0 = never spoils)" },
        food_effects: {
          type: "array",
          description: "For food: effects when eaten (e.g., heal, satiated, stamina_restore, mana_restore, poison, str/dex/con/int/wis/cha_boost, haste, slow, regeneration)",
          items: {
            type: "object",
            properties: {
              effect_type: { type: "string", description: "Effect type: heal, poison, stamina_restore, mana_restore, satiated, quenched, drunk, str_boost, dex_boost, con_boost, int_boost, wis_boost, cha_boost, haste, slow, invisibility, detect_invisible, regeneration" },
              magnitude: { type: "number", description: "Effect strength" },
              duration: { type: "number", description: "Duration in seconds (0 = instant)" },
            },
            required: ["effect_type", "magnitude"],
          },
        },
        note_content: { type: "string", description: "Long-form readable body (use \\n for line breaks). Any item with this becomes readable via the `read` command; ANSI and whitespace are preserved. Max 32 KB." },
      },
      required: ["name", "short_desc", "long_desc", "vnum", "item_type"],
    },
  },
  {
    name: "update_item",
    description: "Update an existing item",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Item UUID or vnum" },
        name: { type: "string" },
        short_desc: { type: "string" },
        long_desc: { type: "string" },
        vnum: { type: "string", description: "New vnum (must be unique)" },
        item_type: { type: "string", enum: ["misc", "armor", "weapon", "container", "liquid_container", "food", "key", "gold"], description: "Change item type" },
        keywords: { type: "array", items: { type: "string" } },
        weight: { type: "number" },
        value: { type: "number" },
        categories: {
          type: "array",
          items: { type: "string" },
          description: "Crafting / shop-filter categories. Passing this replaces the existing categories list.",
        },
        flags: { type: "object" },
        damage_dice_count: { type: "number", description: "For weapons: dice count (e.g., 2 in 2d6)" },
        damage_dice_sides: { type: "number", description: "For weapons: dice sides (e.g., 6 in 2d6)" },
        damage_type: {
          type: "string",
          enum: ["bludgeoning", "slashing", "piercing", "fire", "cold", "lightning", "poison", "acid"],
        },
        armor_class: { type: "number", description: "For armor: AC bonus" },
        wear_location: {
          type: "string",
          enum: ["head", "neck", "shoulders", "back", "torso", "waist", "ears",
                 "wielded", "offhand", "ready",
                 "leftarm", "rightarm", "leftwrist", "rightwrist",
                 "lefthand", "righthand", "leftfinger", "rightfinger",
                 "leftleg", "rightleg", "leftankle", "rightankle",
                 "leftfoot", "rightfoot"],
        },
        weapon_skill: {
          type: "string",
          enum: ["short_blades", "long_blades", "short_blunt", "long_blunt", "polearms", "unarmed", "ranged"],
        },
        caliber: { type: "string" },
        ranged_type: { type: "string" },
        magazine_size: { type: "number" },
        fire_mode: { type: "string" },
        supported_fire_modes: { type: "array", items: { type: "string" } },
        noise_level: { type: "string" },
        two_handed: { type: "boolean" },
        ammo_count: { type: "number" },
        ammo_damage_bonus: { type: "number" },
        attachment_slot: { type: "string" },
        attachment_accuracy_bonus: { type: "number" },
        attachment_noise_reduction: { type: "number" },
        attachment_magazine_bonus: { type: "number" },
        plant_prototype_vnum: { type: "string", description: "For seeds: plant prototype vnum this seed grows into" },
        fertilizer_duration: { type: "number", description: "For fertilizer: duration in game hours" },
        treats_infestation: { type: "string", description: "For pest treatment: type treated (aphids, blight, root_rot, frost, all)" },
        liquid_type: { type: "string", description: "For liquid_container: liquid type. Changing the type always re-applies that type's default effects, replacing any stale effects from the previous type. Pass `liquid_effects` alongside to override with custom effects." },
        liquid_current: { type: "number", description: "For liquid_container: current sips" },
        liquid_max: { type: "number", description: "For liquid_container: maximum sips" },
        liquid_effects: {
          type: "array",
          description: "For liquid_container: explicit effects, overriding any defaults. Applied AFTER liquid_type changes, so if passed together it wins over the type's defaults.",
          items: {
            type: "object",
            properties: {
              effect_type: { type: "string", description: "Effect type (e.g., drunk, quenched, stamina_restore, mana_restore, heal, poison)" },
              magnitude: { type: "number", description: "Effect strength" },
              duration: { type: "number", description: "Duration in seconds (0 = instant)" },
            },
            required: ["effect_type", "magnitude"],
          },
        },
        medical_tier: { type: "number", description: "Medical tier: 1=basic, 2=intermediate, 3=advanced" },
        medical_uses: { type: "number", description: "Medical uses: 0=reusable, >0=consumable" },
        treats_wound_types: { type: "array", items: { type: "string" }, description: "Wound types this item treats" },
        food_nutrition: { type: "number", description: "For food: nutrition value" },
        food_spoil_duration: { type: "number", description: "For food: spoilage time in game hours (0 = never)" },
        food_effects: {
          type: "array",
          description: "For food: effects when eaten",
          items: {
            type: "object",
            properties: {
              effect_type: { type: "string", description: "Effect type (e.g., heal, satiated, stamina_restore, mana_restore)" },
              magnitude: { type: "number", description: "Effect strength" },
              duration: { type: "number", description: "Duration in seconds (0 = instant)" },
            },
            required: ["effect_type", "magnitude"],
          },
        },
        note_content: { type: "string", description: "Long-form readable body (use \\n for line breaks). Any item with this becomes readable via the `read` command; ANSI and whitespace are preserved. Empty string clears. Max 32 KB." },
      },
      required: ["id"],
    },
  },
  {
    name: "delete_item",
    description: "Delete an item",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Item UUID or vnum" },
      },
      required: ["id"],
    },
  },
  {
    name: "spawn_item",
    description: "Spawn an item instance from a prototype into a room",
    inputSchema: {
      type: "object",
      properties: {
        vnum: { type: "string", description: "Item prototype vnum" },
        room_id: { type: "string", description: "Target room UUID or vnum" },
      },
      required: ["vnum", "room_id"],
    },
  },
];
