import { onHitEffectsSchema } from "./items.js";

export const mobileToolDefinitions = [
  {
    name: "list_mobiles",
    description: "List all mobiles",
    inputSchema: {
      type: "object",
      properties: {
        limit: { type: "number", default: 100 },
        offset: { type: "number", default: 0 },
      },
    },
  },
  {
    name: "list_mobile_prototypes",
    description: "List only mobile prototypes (templates). WARNING: Returns full entity data. Prefer list_mobile_prototypes_summary for discovery.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "list_mobile_prototypes_summary",
    description: "List mobile prototype summaries (compact: vnum, name, level, hp, flags). Use for discovery, then get_mobile by vnum for detail.",
    inputSchema: {
      type: "object",
      properties: {
        vnum_prefix: {
          type: "string",
          description: "Filter by vnum prefix (e.g., 'training' to match 'training:*')",
        },
      },
    },
  },
  {
    name: "get_mobile",
    description: "Get a mobile by UUID or vnum",
    inputSchema: {
      type: "object",
      properties: {
        identifier: { type: "string", description: "Mobile UUID or vnum" },
      },
      required: ["identifier"],
    },
  },
  {
    name: "create_mobile",
    description: "Create a new mobile prototype (NPC template)",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Mobile name (e.g., 'a goblin guard')" },
        short_desc: { type: "string", description: "Room description (e.g., 'A goblin guard stands here.')" },
        long_desc: { type: "string", description: "Full description when examined" },
        vnum: { type: "string", description: "Unique vnum (e.g., 'forest:wolf')" },
        area_id: { type: "string", description: "Optional owning area UUID. Caller must have edit rights on it (per AreaPermission). Omit/empty for an orphan prototype editable by any builder." },
        keywords: { type: "array", items: { type: "string" } },
        level: { type: "number", default: 1 },
        max_hp: { type: "number", default: 20 },
        damage_dice: { type: "string", description: "Damage dice (e.g., '2d4+2')" },
        armor_class: { type: "number", default: 10 },
        flags: {
          type: "object",
          properties: {
            aggressive: { type: "boolean", description: "Attacks players on sight" },
            sentinel: { type: "boolean", description: "Does not wander" },
            scavenger: { type: "boolean", description: "Picks up items" },
            shopkeeper: { type: "boolean", description: "Can buy/sell items" },
            healer: { type: "boolean", description: "Can heal players" },
            no_attack: { type: "boolean", description: "Cannot be attacked" },
            cowardly: { type: "boolean", description: "Flees when HP is low" },
            can_open_doors: { type: "boolean", description: "Can open/unlock doors during pathfinding" },
            leasing_agent: { type: "boolean", description: "Can rent out property templates" },
            guard: { type: "boolean", description: "Enhanced perception, responds to nearby theft" },
            helper: { type: "boolean", description: "Joins combat to defend faction allies attacked by a player. Empty/missing `faction` falls back to Circle-stock semantics (any NPC defends any other NPC)." },
            thief: { type: "boolean", description: "Steals gold from players" },
            cant_swim: { type: "boolean", description: "Cannot enter water rooms, takes damage if in water" },
            poisonous: { type: "boolean", description: "Melee hits apply a poison DoT (3 rounds, scaled by level)" },
            fiery: { type: "boolean", description: "Melee hits apply a fire DoT (3 rounds, scaled by level)" },
            chilling: { type: "boolean", description: "Melee hits apply a cold DoT (3 rounds, scaled by level)" },
            corrosive: { type: "boolean", description: "Melee hits apply an acid DoT (3 rounds, scaled by level)" },
            shocking: { type: "boolean", description: "Melee hits apply a lightning DoT (3 rounds, scaled by level)" },
            unique: { type: "boolean", description: "Only one live (non-prototype) instance of this vnum allowed in the world. Sugar for `world_max_count = 1`." },
            stay_zone: { type: "boolean", description: "Wandering and pursuit stay inside the mobile's home area (set at first room placement). CircleMUD MOB_STAY_ZONE parity." },
            aware: { type: "boolean", description: "Sees through hidden / sneaking / invisibility when picking aggression/memory targets. CircleMUD MOB_AWARE parity." },
            memory: { type: "boolean", description: "Remembers PC attackers for 30 minutes (max 10) and attacks on sight even after combat ends. CircleMUD MOB_MEMORY parity." },
            no_sleep: { type: "boolean", description: "Immune to the sleep spell. CircleMUD MOB_NOSLEEP parity." },
            no_blind: { type: "boolean", description: "Immune to the blind spell. CircleMUD MOB_NOBLIND parity." },
            no_bash: { type: "boolean", description: "Immune to the bash skill (no stun, no damage). CircleMUD MOB_NOBASH parity." },
            no_summon: { type: "boolean", description: "Immune to the summon spell. CircleMUD MOB_NOSUMMON parity." },
            no_charm: { type: "boolean", description: "Immune to the charm spell. CircleMUD MOB_NOCHARM parity." },
            hostile_on_steal: { type: "boolean", description: "Attacks the thief when a steal attempt is caught. CircleMUD shop WILL_START_FIGHT parity (now general-purpose; works on any mob, not just shopkeepers)." },
            tameable: { type: "boolean", description: "Casting `charm` on this mob installs a permanent pet bond (writes `pet_owner`) instead of the regular 5-minute charm buff. Use for animals/familiars that should survive logout." },
            aggro_good: { type: "boolean", description: "Attacks players with morality > 24 (any Good tier). CircleMUD MOB_AGGR_GOOD parity." },
            aggro_evil: { type: "boolean", description: "Attacks players with morality < -24 (any Evil tier). CircleMUD MOB_AGGR_EVIL parity." },
            aggro_neutral: { type: "boolean", description: "Attacks players with -24 <= morality <= 24 (Neutral). CircleMUD MOB_AGGR_NEUTRAL parity." },
          },
        },
        position: { type: "string", enum: ["standing", "sitting", "sleeping"], description: "Default physical stance for spawned instances. Sleeping mobs skip combat turns until damaged; damage transitions Sleeping → Sitting." },
        creature_type: { type: "string", enum: ["mortal", "animal", "insect", "plant", "construct", "spirit"], description: "Base biology. Drives vampire feeding: Mortal yields full blood (humanity cost on lethal innocent kill); Animal yields reduced blood at no humanity cost; Insect/Plant/Construct/Spirit are unfeedable. Independent of the undead/vampire state flags. Defaults to mortal." },
        gender: { type: "string", description: "Authored gender for DG pronouns (e.g. \"male\", \"female\", \"nonbinary\"). Free string accepted; unrecognised values resolve to neuter pronouns. Lazy-instantiates `Characteristics` if absent." },
        perception: { type: "number", description: "Stealth detection ability (0-10, default 0)" },
        world_max_count: { type: "number", description: "Cap on live (non-prototype) instances of this vnum world-wide. Omit or 0 = unlimited. `flags.unique` is sugar for 1." },
        faction: { type: "string", description: "Helper-system ally tag. Mobiles with the same faction string defend each other when `flags.helper` is set. Omit/empty = Circle-stock fallback (any NPC defends any other NPC)." },
        spoken_language: { type: "string", description: "Language key (e.g. \"orcish\", \"elvish\"). Listeners with low skill in the language hear the mob's say-line garbled; admins and lingua-franca speakers always hear plaintext. Omit/empty = no garble (mob speaks Common)." },
        combat_spells: { type: "array", items: { type: "string" }, description: "Spell IDs (e.g. 'magic_missile', 'firebolt') the mob may cast in combat. CircleMUD `magic_user` specproc analog. Each combat round rolls `combat_spell_chance`; on success a random spell from the list is cast at the player target instead of swinging melee." },
        combat_spell_chance: { type: "number", description: "Per-round percent chance (0-100) to cast from `combat_spells` rather than swinging. Default 50; ignored when `combat_spells` is empty." },
        on_hit_effects: onHitEffectsSchema,
        healer_type: { type: "string", description: "Healer specialization type" },
        healing_free: { type: "boolean", description: "Whether healing is free" },
        healing_cost_multiplier: { type: "number", description: "Healing cost multiplier (default 100)" },
        shop_sell_rate: { type: "number", description: "Shop sell rate percentage (default 150)" },
        shop_buy_rate: { type: "number", description: "Shop buy rate percentage (default 50)" },
        shop_buys_types: { type: "array", items: { type: "string" }, description: "Item types the shop buys (e.g., 'misc', 'weapon', 'armor'). An item must match one of these to be buyable." },
        shop_buys_categories: { type: "array", items: { type: "string" }, description: "Item categories the shop buys (e.g., 'flowers', 'herbs'). Item must match one of these AND pass type filter." },
        shop_min_value: { type: "number", description: "Minimum item value the shop will buy (0 = no minimum)" },
        shop_max_value: { type: "number", description: "Maximum item value the shop will buy (0 = no maximum)" },
        shop_extra_types: { type: "array", items: { type: "string" }, description: "Extra item types added on top of shop_preset_vnum" },
        shop_extra_categories: { type: "array", items: { type: "string" }, description: "Extra categories added on top of shop_preset_vnum" },
        shop_deny_types: { type: "array", items: { type: "string" }, description: "Item types excluded from shop_preset_vnum" },
        shop_deny_categories: { type: "array", items: { type: "string" }, description: "Categories excluded from shop_preset_vnum" },
        shop_stock: { type: "array", items: { type: "string" }, description: "Item vnums for shop stock (infinite supply)" },
        shop_preset_vnum: { type: "string", description: "Shop buy preset vnum (managed via bpredit)" },
        daily_routine: {
          type: "array",
          items: {
            type: "object",
            properties: {
              start_hour: { type: "number", description: "Game hour (0-23) when this entry activates" },
              activity: { type: "string", description: "Activity state: working, sleeping, patrolling, offduty, socializing, eating, or custom string" },
              destination_vnum: { type: "string", description: "Room vnum to walk to" },
              transition_message: { type: "string", description: "Message broadcast when transitioning" },
              suppress_wander: { type: "boolean", description: "Suppress random wandering" },
              dialogue_overrides: { type: "object", description: "Dialogue keyword overrides for this period" },
            },
            required: ["start_hour", "activity"],
          },
          description: "Daily routine schedule entries",
        },
        simulation: {
          type: "object",
          description: "Needs simulation config. When set, NPC autonomously works, buys food, eats, and sleeps based on decaying needs (hunger, energy, comfort). Overrides daily_routine.",
          properties: {
            home_room_vnum: { type: "string", description: "Room vnum where NPC lives/sleeps" },
            work_room_vnum: { type: "string", description: "Room vnum where NPC works" },
            shop_room_vnum: { type: "string", description: "Room vnum of preferred food shop" },
            preferred_food_vnum: { type: "string", description: "Preferred food item vnum to purchase" },
            work_pay: { type: "number", description: "Gold earned per work shift (default 50)" },
            work_start_hour: { type: "number", description: "Game hour work starts (default 8)" },
            work_end_hour: { type: "number", description: "Game hour work ends (default 17)" },
            hunger_decay_rate: { type: "number", description: "Hunger decay multiplier (100=normal, 200=2x, 0=default)" },
            energy_decay_rate: { type: "number", description: "Energy decay multiplier" },
            comfort_decay_rate: { type: "number", description: "Comfort decay multiplier" },
            low_gold_threshold: { type: "number", description: "Gold balance at or below which the NPC prioritizes work over food (default 10). Treats low money as a need so broke NPCs go earn instead of looping at the shop." },
          },
          required: ["home_room_vnum", "work_room_vnum"],
        },
      },
      required: ["name", "short_desc", "long_desc", "vnum"],
    },
  },
  {
    name: "update_mobile",
    description: "Update an existing mobile",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Mobile UUID or vnum" },
        name: { type: "string" },
        short_desc: { type: "string" },
        long_desc: { type: "string" },
        vnum: { type: "string", description: "New vnum (must be unique)" },
        area_id: { type: "string", description: "Reassign owning area. Empty string clears the assignment back to orphan. Caller must have edit rights on both current and target areas." },
        keywords: { type: "array", items: { type: "string" } },
        level: { type: "number" },
        max_hp: { type: "number" },
        armor_class: { type: "number" },
        gold: { type: "number", description: "Gold carried by this mobile" },
        flags: {
          type: "object",
          properties: {
            aggressive: { type: "boolean" },
            sentinel: { type: "boolean" },
            scavenger: { type: "boolean" },
            shopkeeper: { type: "boolean" },
            healer: { type: "boolean" },
            no_attack: { type: "boolean" },
            cowardly: { type: "boolean" },
            can_open_doors: { type: "boolean" },
            leasing_agent: { type: "boolean" },
            guard: { type: "boolean" },
            helper: { type: "boolean" },
            thief: { type: "boolean" },
            cant_swim: { type: "boolean" },
            poisonous: { type: "boolean" },
            fiery: { type: "boolean" },
            chilling: { type: "boolean" },
            corrosive: { type: "boolean" },
            shocking: { type: "boolean" },
            unique: { type: "boolean" },
            stay_zone: { type: "boolean" },
            aware: { type: "boolean" },
            memory: { type: "boolean" },
            no_sleep: { type: "boolean" },
            no_blind: { type: "boolean" },
            no_bash: { type: "boolean" },
            no_summon: { type: "boolean" },
            no_charm: { type: "boolean" },
            hostile_on_steal: { type: "boolean" },
            tameable: { type: "boolean" },
            aggro_good: { type: "boolean" },
            aggro_evil: { type: "boolean" },
            aggro_neutral: { type: "boolean" },
          },
        },
        position: { type: "string", enum: ["standing", "sitting", "sleeping"], description: "Set the mobile's physical stance." },
        creature_type: { type: "string", enum: ["mortal", "animal", "insect", "plant", "construct", "spirit"], description: "Set the base biology (drives vampire feeding; independent of undead/vampire flags). Unrecognised values leave it unchanged." },
        gender: { type: "string", description: "Set authored gender. Empty string clears (preserves other Characteristics fields). Free string accepted; DG falls back to neuter for unrecognised values." },
        perception: { type: "number" },
        world_max_count: { type: "number", description: "Cap on live (non-prototype) instances of this vnum world-wide. 0 or negative clears the cap (unlimited)." },
        dialogue_tree: {
          type: "object",
          description: "Branching dialogue tree. Shape: { root_node: 'root', nodes: { <id>: { text, choices: [{ keyword, label, target: { kind: 'goto'|'exit'|'repeat', node? }, conditions: [...], effects: [...] }], on_enter: [...] } } }. Conditions use kind: flag_set/flag_unset/has_item/skill_at_least/counter_at_least/dg_var_equals/quest_active/quest_complete/quest_completable/humanity_at_least/is_thinblood/is_clan_acknowledged/has_achievement/quest_choice_equals. Effects use kind: set_flag/clear_flag/give_item/take_item/award_skill_xp/set_counter/increment_counter/set_dg_var/fire_dg_trigger/offer_quest/complete_quest/abandon_quest/set_quest_choice. Flag scope is 'local' (per-mob-vnum) or 'global'. DG scope is 'player' or 'mob'. quest_choice_equals/set_quest_choice operate on ActiveQuest.choice_vars and are typically paired (record a player pick, then read it later in the same tree or in a reward).",
          additionalProperties: true,
        },
        clear_dialogue_tree: { type: "boolean", description: "Pass true to remove the dialogue tree. Takes precedence over `dialogue_tree`." },
        faction: { type: "string", description: "Helper-system ally tag. Empty string clears." },
        spoken_language: { type: "string", description: "Language key (e.g. \"orcish\"). Empty string clears (mob speaks Common). Unknown keys are rejected." },
        combat_spells: { type: "array", items: { type: "string" }, description: "Replace the spell list. Empty array clears." },
        combat_spell_chance: { type: "number", description: "Per-round percent chance (0-100) to cast from `combat_spells`. Out-of-range values are clamped." },
        on_hit_effects: onHitEffectsSchema,
        healer_type: { type: "string" },
        healing_free: { type: "boolean" },
        healing_cost_multiplier: { type: "number" },
        shop_sell_rate: { type: "number" },
        shop_buy_rate: { type: "number" },
        shop_buys_types: { type: "array", items: { type: "string" } },
        shop_buys_categories: { type: "array", items: { type: "string" }, description: "Item categories the shop buys" },
        shop_min_value: { type: "number", description: "Minimum item value the shop will buy (0 = no minimum)" },
        shop_max_value: { type: "number", description: "Maximum item value the shop will buy (0 = no maximum)" },
        shop_extra_types: { type: "array", items: { type: "string" } },
        shop_extra_categories: { type: "array", items: { type: "string" } },
        shop_deny_types: { type: "array", items: { type: "string" } },
        shop_deny_categories: { type: "array", items: { type: "string" } },
        shop_stock: { type: "array", items: { type: "string" } },
        shop_preset_vnum: { type: "string" },
        daily_routine: {
          type: "array",
          items: {
            type: "object",
            properties: {
              start_hour: { type: "number" },
              activity: { type: "string" },
              destination_vnum: { type: "string" },
              transition_message: { type: "string" },
              suppress_wander: { type: "boolean" },
              dialogue_overrides: { type: "object" },
            },
            required: ["start_hour", "activity"],
          },
        },
        simulation: {
          type: "object",
          description: "Needs simulation config. Overrides daily_routine with autonomous behavior.",
          properties: {
            home_room_vnum: { type: "string" },
            work_room_vnum: { type: "string" },
            shop_room_vnum: { type: "string" },
            preferred_food_vnum: { type: "string" },
            work_pay: { type: "number" },
            work_start_hour: { type: "number" },
            work_end_hour: { type: "number" },
            hunger_decay_rate: { type: "number" },
            energy_decay_rate: { type: "number" },
            comfort_decay_rate: { type: "number" },
            low_gold_threshold: { type: "number", description: "Gold threshold at or below which the NPC prioritizes work over food (default 10)." },
          },
          required: ["home_room_vnum", "work_room_vnum"],
        },
        remove_simulation: { type: "boolean", description: "Set to true to remove simulation config and disable needs system" },
      },
      required: ["id"],
    },
  },
  {
    name: "delete_mobile",
    description: "Delete a mobile",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Mobile UUID or vnum" },
      },
      required: ["id"],
    },
  },
  {
    name: "add_mobile_dialogue",
    description: "Add a dialogue response to a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        keyword: { type: "string", description: "Trigger keyword (e.g., 'hello')" },
        response: { type: "string", description: "Mobile's response text" },
      },
      required: ["mobile_id", "keyword", "response"],
    },
  },
  {
    name: "remove_mobile_dialogue",
    description: "Remove a dialogue entry from a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        keyword: { type: "string", description: "Keyword to remove" },
      },
      required: ["mobile_id", "keyword"],
    },
  },
  // ===== Granular dialogue-tree editing =====
  // Compose a tree node-by-node, choice-by-choice. Adding the very first
  // node auto-initializes the tree with that node as the root.
  {
    name: "set_mobile_dialogue_tree_root",
    description: "Point the dialogue tree's root_node at an existing node (the entry point reached by 'talk <mob>' before any state).",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        node_name: { type: "string", description: "Existing node id to use as root" },
      },
      required: ["mobile_id", "node_name"],
    },
  },
  {
    name: "add_mobile_dialogue_node",
    description: "Add a new node to a mobile's dialogue tree. If the mobile has no tree yet, the first node added becomes the tree's root.",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        name: { type: "string", description: "Node id (used by Goto choice targets and for later updates)" },
        text: { type: "string", description: "Mob's spoken text when this node is entered" },
        on_enter: { type: "array", description: "Effects fired the FIRST time this player visits this node (DialogueEffect[])" },
        on_each_visit: { type: "array", description: "Effects fired EVERY time this player enters this node, including the first" },
        on_exit: { type: "array", description: "Effects fired when leaving this node (Goto away or Exit)" },
      },
      required: ["mobile_id", "name", "text"],
    },
  },
  {
    name: "update_mobile_dialogue_node",
    description: "Patch fields of an existing node. Omit a field to leave it unchanged. Pass [] to clear an effect list.",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        node_name: { type: "string", description: "Node id to patch" },
        text: { type: "string", description: "New spoken text" },
        on_enter: { type: "array", description: "Replacement on_enter effect list" },
        on_each_visit: { type: "array", description: "Replacement on_each_visit effect list" },
        on_exit: { type: "array", description: "Replacement on_exit effect list" },
      },
      required: ["mobile_id", "node_name"],
    },
  },
  {
    name: "remove_mobile_dialogue_node",
    description: "Remove a node from the tree. Errors if it is the root, or if any other node has a Goto pointing at it (re-route those choices first).",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        node_name: { type: "string", description: "Node id to remove" },
      },
      required: ["mobile_id", "node_name"],
    },
  },
  {
    name: "add_mobile_dialogue_choice",
    description: "Append a choice to a node. The keyword is matched by 'say <keyword>'; the label is shown in 'talk' menus. Goto targets must reference an existing node.",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        node_name: { type: "string", description: "Node id to attach the choice to" },
        keyword: { type: "string", description: "Single-word lookup key (case-insensitive)" },
        label: { type: "string", description: "Human-readable label for the talk menu" },
        target: { type: "object", description: "DialogueTarget: {kind:'goto', node:'X'} | {kind:'exit'} | {kind:'repeat'}" },
        conditions: { type: "array", description: "DialogueCondition[] — choice is hidden unless ALL evaluate true" },
        effects: { type: "array", description: "DialogueEffect[] fired when the player picks this choice" },
        hint: { type: "string", description: "Optional flavor line shown in place of the choice when its conditions fail. Empty/omitted = silently hide (default)." },
        cooldown_secs: { type: "number", description: "Optional per-player cooldown in seconds. After picking, the choice renders as '(available in Xm)' until the timer elapses. 0 or omitted = no cooldown." },
        once_per_player: { type: "boolean", description: "If true, the choice can only be picked once per player per mob vnum. Disappears from the menu after the first pick." },
      },
      required: ["mobile_id", "node_name", "keyword", "label", "target"],
    },
  },
  {
    name: "update_mobile_dialogue_choice",
    description: "Replace a choice at the given index on a node (0-indexed). Index is the choice's position in the node's choices array.",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        node_name: { type: "string", description: "Node id" },
        index: { type: "number", description: "0-indexed position of the choice to replace" },
        keyword: { type: "string" },
        label: { type: "string" },
        target: { type: "object" },
        conditions: { type: "array" },
        effects: { type: "array" },
        hint: { type: "string", description: "Flavor line for failed-condition rendering. Empty string clears." },
        cooldown_secs: { type: "number", description: "Per-player cooldown in seconds (0 clears)." },
        once_per_player: { type: "boolean", description: "Pick-once-ever flag (false clears)." },
      },
      required: ["mobile_id", "node_name", "index", "keyword", "label", "target"],
    },
  },
  {
    name: "remove_mobile_dialogue_choice",
    description: "Remove a choice at the given index from a node (0-indexed).",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        node_name: { type: "string", description: "Node id" },
        index: { type: "number", description: "0-indexed position" },
      },
      required: ["mobile_id", "node_name", "index"],
    },
  },
  {
    name: "add_mobile_routine",
    description: "Add a daily routine entry to a mobile (schedule-based behavior)",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        start_hour: { type: "number", description: "Game hour (0-23) when this entry activates" },
        activity: { type: "string", description: "Activity state: working, sleeping, patrolling, offduty, socializing, eating, or custom string" },
        destination_vnum: { type: "string", description: "Room vnum to walk to when this entry activates" },
        transition_message: { type: "string", description: "Message broadcast when transitioning (e.g., 'opens his shop')" },
        suppress_wander: { type: "boolean", description: "Suppress random wandering during this period" },
        dialogue_overrides: { type: "object", description: "Dialogue keyword overrides active during this period" },
      },
      required: ["mobile_id", "start_hour", "activity"],
    },
  },
  {
    name: "remove_mobile_routine",
    description: "Remove a daily routine entry from a mobile by index",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        index: { type: "number", description: "Routine entry index to remove" },
      },
      required: ["mobile_id", "index"],
    },
  },
  {
    name: "spawn_mobile",
    description: "Spawn a mobile instance from a prototype into a room",
    inputSchema: {
      type: "object",
      properties: {
        vnum: { type: "string", description: "Mobile prototype vnum" },
        room_id: { type: "string", description: "Target room UUID or vnum" },
      },
      required: ["vnum", "room_id"],
    },
  },
  {
    name: "add_mobile_trigger",
    description: "Add a trigger script to a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        trigger_type: {
          type: "string",
          enum: ["greet", "attack", "death", "say", "idle", "always", "flee"],
          description: "Trigger type",
        },
        script_name: { type: "string", description: "Script filename without extension" },
        enabled: { type: "boolean", default: true },
        interval_secs: { type: "number", description: "For idle triggers" },
        chance: { type: "number", description: "Trigger probability (0-100)" },
        args: { type: "array", items: { type: "string" } },
      },
      required: ["mobile_id", "trigger_type", "script_name"],
    },
  },
  {
    name: "remove_mobile_trigger",
    description: "Remove a trigger from a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        index: { type: "number", description: "Trigger index to remove" },
      },
      required: ["mobile_id", "index"],
    },
  },
  {
    name: "list_mobile_presets",
    description:
      "List available mobile presets (data-driven flag/stat bundles in scripts/data/mobile_presets.json). Optional tag filter. Each preset returns { id, name, description, tags } so builders can pick one before applying.",
    inputSchema: {
      type: "object",
      properties: {
        tag: {
          type: "string",
          description: "Optional tag filter (e.g. 'vampire', 'guard', 'beast'). Empty = all presets.",
        },
      },
    },
  },
  {
    name: "apply_mobile_preset",
    description:
      "Apply a preset's flags + stats + on-hit effects to an existing mobile prototype or instance. Flags are additive (only the flags listed in the preset change); stat overrides only fire when the preset includes that field. Use list_mobile_presets first to see what's available.",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID (instance or prototype)" },
        preset_id: {
          type: "string",
          description:
            "Preset id from list_mobile_presets (e.g. 'vampire_goon', 'town_guard_captain', 'dire_wolf')",
        },
      },
      required: ["mobile_id", "preset_id"],
    },
  },
];
