export const mobileToolDefinitions = [
  {
    name: "list_mobiles",
    description: "List all mobiles",
    inputSchema: {
      type: "object",
      properties: {
        limit: { type: "number", default: 100 },
        offset: { type: "number", default: 0 },
      },
    },
  },
  {
    name: "list_mobile_prototypes",
    description: "List only mobile prototypes (templates). WARNING: Returns full entity data. Prefer list_mobile_prototypes_summary for discovery.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "list_mobile_prototypes_summary",
    description: "List mobile prototype summaries (compact: vnum, name, level, hp, flags). Use for discovery, then get_mobile by vnum for detail.",
    inputSchema: {
      type: "object",
      properties: {
        vnum_prefix: {
          type: "string",
          description: "Filter by vnum prefix (e.g., 'training' to match 'training:*')",
        },
      },
    },
  },
  {
    name: "get_mobile",
    description: "Get a mobile by UUID or vnum",
    inputSchema: {
      type: "object",
      properties: {
        identifier: { type: "string", description: "Mobile UUID or vnum" },
      },
      required: ["identifier"],
    },
  },
  {
    name: "create_mobile",
    description: "Create a new mobile prototype (NPC template)",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Mobile name (e.g., 'a goblin guard')" },
        short_desc: { type: "string", description: "Room description (e.g., 'A goblin guard stands here.')" },
        long_desc: { type: "string", description: "Full description when examined" },
        vnum: { type: "string", description: "Unique vnum (e.g., 'forest:wolf')" },
        keywords: { type: "array", items: { type: "string" } },
        level: { type: "number", default: 1 },
        max_hp: { type: "number", default: 20 },
        damage_dice: { type: "string", description: "Damage dice (e.g., '2d4+2')" },
        armor_class: { type: "number", default: 10 },
        flags: {
          type: "object",
          properties: {
            aggressive: { type: "boolean", description: "Attacks players on sight" },
            sentinel: { type: "boolean", description: "Does not wander" },
            scavenger: { type: "boolean", description: "Picks up items" },
            shopkeeper: { type: "boolean", description: "Can buy/sell items" },
            healer: { type: "boolean", description: "Can heal players" },
            no_attack: { type: "boolean", description: "Cannot be attacked" },
            cowardly: { type: "boolean", description: "Flees when HP is low" },
            can_open_doors: { type: "boolean", description: "Can open/unlock doors during pathfinding" },
            leasing_agent: { type: "boolean", description: "Can rent out property templates" },
            guard: { type: "boolean", description: "Enhanced perception, responds to nearby theft" },
            helper: { type: "boolean", description: "Joins combat to defend faction allies attacked by a player. Empty/missing `faction` falls back to Circle-stock semantics (any NPC defends any other NPC)." },
            thief: { type: "boolean", description: "Steals gold from players" },
            cant_swim: { type: "boolean", description: "Cannot enter water rooms, takes damage if in water" },
            poisonous: { type: "boolean", description: "Melee hits apply a poison DoT (3 rounds, scaled by level)" },
            fiery: { type: "boolean", description: "Melee hits apply a fire DoT (3 rounds, scaled by level)" },
            chilling: { type: "boolean", description: "Melee hits apply a cold DoT (3 rounds, scaled by level)" },
            corrosive: { type: "boolean", description: "Melee hits apply an acid DoT (3 rounds, scaled by level)" },
            shocking: { type: "boolean", description: "Melee hits apply a lightning DoT (3 rounds, scaled by level)" },
            unique: { type: "boolean", description: "Only one live (non-prototype) instance of this vnum allowed in the world. Sugar for `world_max_count = 1`." },
            stay_zone: { type: "boolean", description: "Wandering and pursuit stay inside the mobile's home area (set at first room placement). CircleMUD MOB_STAY_ZONE parity." },
            aware: { type: "boolean", description: "Sees through hidden / sneaking / invisibility when picking aggression/memory targets. CircleMUD MOB_AWARE parity." },
            memory: { type: "boolean", description: "Remembers PC attackers for 30 minutes (max 10) and attacks on sight even after combat ends. CircleMUD MOB_MEMORY parity." },
          },
        },
        perception: { type: "number", description: "Stealth detection ability (0-10, default 0)" },
        world_max_count: { type: "number", description: "Cap on live (non-prototype) instances of this vnum world-wide. Omit or 0 = unlimited. `flags.unique` is sugar for 1." },
        faction: { type: "string", description: "Helper-system ally tag. Mobiles with the same faction string defend each other when `flags.helper` is set. Omit/empty = Circle-stock fallback (any NPC defends any other NPC)." },
        healer_type: { type: "string", description: "Healer specialization type" },
        healing_free: { type: "boolean", description: "Whether healing is free" },
        healing_cost_multiplier: { type: "number", description: "Healing cost multiplier (default 100)" },
        shop_sell_rate: { type: "number", description: "Shop sell rate percentage (default 150)" },
        shop_buy_rate: { type: "number", description: "Shop buy rate percentage (default 50)" },
        shop_buys_types: { type: "array", items: { type: "string" }, description: "Item types the shop buys (e.g., 'misc', 'weapon', 'armor'). An item must match one of these to be buyable." },
        shop_buys_categories: { type: "array", items: { type: "string" }, description: "Item categories the shop buys (e.g., 'flowers', 'herbs'). Item must match one of these AND pass type filter." },
        shop_min_value: { type: "number", description: "Minimum item value the shop will buy (0 = no minimum)" },
        shop_max_value: { type: "number", description: "Maximum item value the shop will buy (0 = no maximum)" },
        shop_extra_types: { type: "array", items: { type: "string" }, description: "Extra item types added on top of shop_preset_vnum" },
        shop_extra_categories: { type: "array", items: { type: "string" }, description: "Extra categories added on top of shop_preset_vnum" },
        shop_deny_types: { type: "array", items: { type: "string" }, description: "Item types excluded from shop_preset_vnum" },
        shop_deny_categories: { type: "array", items: { type: "string" }, description: "Categories excluded from shop_preset_vnum" },
        shop_stock: { type: "array", items: { type: "string" }, description: "Item vnums for shop stock (infinite supply)" },
        shop_preset_vnum: { type: "string", description: "Shop buy preset vnum (managed via bpredit)" },
        daily_routine: {
          type: "array",
          items: {
            type: "object",
            properties: {
              start_hour: { type: "number", description: "Game hour (0-23) when this entry activates" },
              activity: { type: "string", description: "Activity state: working, sleeping, patrolling, offduty, socializing, eating, or custom string" },
              destination_vnum: { type: "string", description: "Room vnum to walk to" },
              transition_message: { type: "string", description: "Message broadcast when transitioning" },
              suppress_wander: { type: "boolean", description: "Suppress random wandering" },
              dialogue_overrides: { type: "object", description: "Dialogue keyword overrides for this period" },
            },
            required: ["start_hour", "activity"],
          },
          description: "Daily routine schedule entries",
        },
        simulation: {
          type: "object",
          description: "Needs simulation config. When set, NPC autonomously works, buys food, eats, and sleeps based on decaying needs (hunger, energy, comfort). Overrides daily_routine.",
          properties: {
            home_room_vnum: { type: "string", description: "Room vnum where NPC lives/sleeps" },
            work_room_vnum: { type: "string", description: "Room vnum where NPC works" },
            shop_room_vnum: { type: "string", description: "Room vnum of preferred food shop" },
            preferred_food_vnum: { type: "string", description: "Preferred food item vnum to purchase" },
            work_pay: { type: "number", description: "Gold earned per work shift (default 50)" },
            work_start_hour: { type: "number", description: "Game hour work starts (default 8)" },
            work_end_hour: { type: "number", description: "Game hour work ends (default 17)" },
            hunger_decay_rate: { type: "number", description: "Hunger decay multiplier (100=normal, 200=2x, 0=default)" },
            energy_decay_rate: { type: "number", description: "Energy decay multiplier" },
            comfort_decay_rate: { type: "number", description: "Comfort decay multiplier" },
            low_gold_threshold: { type: "number", description: "Gold balance at or below which the NPC prioritizes work over food (default 10). Treats low money as a need so broke NPCs go earn instead of looping at the shop." },
          },
          required: ["home_room_vnum", "work_room_vnum"],
        },
      },
      required: ["name", "short_desc", "long_desc", "vnum"],
    },
  },
  {
    name: "update_mobile",
    description: "Update an existing mobile",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Mobile UUID or vnum" },
        name: { type: "string" },
        short_desc: { type: "string" },
        long_desc: { type: "string" },
        vnum: { type: "string", description: "New vnum (must be unique)" },
        keywords: { type: "array", items: { type: "string" } },
        level: { type: "number" },
        max_hp: { type: "number" },
        armor_class: { type: "number" },
        gold: { type: "number", description: "Gold carried by this mobile" },
        flags: {
          type: "object",
          properties: {
            aggressive: { type: "boolean" },
            sentinel: { type: "boolean" },
            scavenger: { type: "boolean" },
            shopkeeper: { type: "boolean" },
            healer: { type: "boolean" },
            no_attack: { type: "boolean" },
            cowardly: { type: "boolean" },
            can_open_doors: { type: "boolean" },
            leasing_agent: { type: "boolean" },
            guard: { type: "boolean" },
            helper: { type: "boolean" },
            thief: { type: "boolean" },
            cant_swim: { type: "boolean" },
            poisonous: { type: "boolean" },
            fiery: { type: "boolean" },
            chilling: { type: "boolean" },
            corrosive: { type: "boolean" },
            shocking: { type: "boolean" },
            unique: { type: "boolean" },
            stay_zone: { type: "boolean" },
            aware: { type: "boolean" },
            memory: { type: "boolean" },
          },
        },
        perception: { type: "number" },
        world_max_count: { type: "number", description: "Cap on live (non-prototype) instances of this vnum world-wide. 0 or negative clears the cap (unlimited)." },
        faction: { type: "string", description: "Helper-system ally tag. Empty string clears." },
        healer_type: { type: "string" },
        healing_free: { type: "boolean" },
        healing_cost_multiplier: { type: "number" },
        shop_sell_rate: { type: "number" },
        shop_buy_rate: { type: "number" },
        shop_buys_types: { type: "array", items: { type: "string" } },
        shop_buys_categories: { type: "array", items: { type: "string" }, description: "Item categories the shop buys" },
        shop_min_value: { type: "number", description: "Minimum item value the shop will buy (0 = no minimum)" },
        shop_max_value: { type: "number", description: "Maximum item value the shop will buy (0 = no maximum)" },
        shop_extra_types: { type: "array", items: { type: "string" } },
        shop_extra_categories: { type: "array", items: { type: "string" } },
        shop_deny_types: { type: "array", items: { type: "string" } },
        shop_deny_categories: { type: "array", items: { type: "string" } },
        shop_stock: { type: "array", items: { type: "string" } },
        shop_preset_vnum: { type: "string" },
        daily_routine: {
          type: "array",
          items: {
            type: "object",
            properties: {
              start_hour: { type: "number" },
              activity: { type: "string" },
              destination_vnum: { type: "string" },
              transition_message: { type: "string" },
              suppress_wander: { type: "boolean" },
              dialogue_overrides: { type: "object" },
            },
            required: ["start_hour", "activity"],
          },
        },
        simulation: {
          type: "object",
          description: "Needs simulation config. Overrides daily_routine with autonomous behavior.",
          properties: {
            home_room_vnum: { type: "string" },
            work_room_vnum: { type: "string" },
            shop_room_vnum: { type: "string" },
            preferred_food_vnum: { type: "string" },
            work_pay: { type: "number" },
            work_start_hour: { type: "number" },
            work_end_hour: { type: "number" },
            hunger_decay_rate: { type: "number" },
            energy_decay_rate: { type: "number" },
            comfort_decay_rate: { type: "number" },
            low_gold_threshold: { type: "number", description: "Gold threshold at or below which the NPC prioritizes work over food (default 10)." },
          },
          required: ["home_room_vnum", "work_room_vnum"],
        },
        remove_simulation: { type: "boolean", description: "Set to true to remove simulation config and disable needs system" },
      },
      required: ["id"],
    },
  },
  {
    name: "delete_mobile",
    description: "Delete a mobile",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Mobile UUID or vnum" },
      },
      required: ["id"],
    },
  },
  {
    name: "add_mobile_dialogue",
    description: "Add a dialogue response to a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        keyword: { type: "string", description: "Trigger keyword (e.g., 'hello')" },
        response: { type: "string", description: "Mobile's response text" },
      },
      required: ["mobile_id", "keyword", "response"],
    },
  },
  {
    name: "remove_mobile_dialogue",
    description: "Remove a dialogue entry from a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        keyword: { type: "string", description: "Keyword to remove" },
      },
      required: ["mobile_id", "keyword"],
    },
  },
  {
    name: "add_mobile_routine",
    description: "Add a daily routine entry to a mobile (schedule-based behavior)",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        start_hour: { type: "number", description: "Game hour (0-23) when this entry activates" },
        activity: { type: "string", description: "Activity state: working, sleeping, patrolling, offduty, socializing, eating, or custom string" },
        destination_vnum: { type: "string", description: "Room vnum to walk to when this entry activates" },
        transition_message: { type: "string", description: "Message broadcast when transitioning (e.g., 'opens his shop')" },
        suppress_wander: { type: "boolean", description: "Suppress random wandering during this period" },
        dialogue_overrides: { type: "object", description: "Dialogue keyword overrides active during this period" },
      },
      required: ["mobile_id", "start_hour", "activity"],
    },
  },
  {
    name: "remove_mobile_routine",
    description: "Remove a daily routine entry from a mobile by index",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        index: { type: "number", description: "Routine entry index to remove" },
      },
      required: ["mobile_id", "index"],
    },
  },
  {
    name: "spawn_mobile",
    description: "Spawn a mobile instance from a prototype into a room",
    inputSchema: {
      type: "object",
      properties: {
        vnum: { type: "string", description: "Mobile prototype vnum" },
        room_id: { type: "string", description: "Target room UUID or vnum" },
      },
      required: ["vnum", "room_id"],
    },
  },
  {
    name: "add_mobile_trigger",
    description: "Add a trigger script to a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        trigger_type: {
          type: "string",
          enum: ["greet", "attack", "death", "say", "idle", "always", "flee"],
          description: "Trigger type",
        },
        script_name: { type: "string", description: "Script filename without extension" },
        enabled: { type: "boolean", default: true },
        interval_secs: { type: "number", description: "For idle triggers" },
        chance: { type: "number", description: "Trigger probability (0-100)" },
        args: { type: "array", items: { type: "string" } },
      },
      required: ["mobile_id", "trigger_type", "script_name"],
    },
  },
  {
    name: "remove_mobile_trigger",
    description: "Remove a trigger from a mobile",
    inputSchema: {
      type: "object",
      properties: {
        mobile_id: { type: "string", description: "Mobile UUID or vnum" },
        index: { type: "number", description: "Trigger index to remove" },
      },
      required: ["mobile_id", "index"],
    },
  },
];
